#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

my %cfg = (
    deb => {
        i386    => 'deb',
        amd64   => 'deb-amd64',
        #sources => 'deb-src',
    },
    components => [qw(
        main
        restricted
        universe
        multiverse
    )],
    'debian-installer' => {
        ''        => [qw( main restricted universe multiverse )],
        -updates  => [qw( main                                )],
        -security => [qw(                                     )],
    },
    'installer-arch' => {
        ''        => [qw( main restricted universe multiverse )],
        -updates  => [qw( main                                )],
        -security => [qw(                                     )],
    },
    dists => [qw(
        saucy
        raring
        quantal
        precise
        lucid
    )],
    'extra-dists' => [qw( -security -updates )],
    uri => 'http://ftp.caliu.cat/ubuntu',
);

print <DATA>;

local $, = q( );

for my $dist ( @{ $cfg{dists} } ) {
    for my $arch ( keys %{ $cfg{deb} } ) {
        for my $component ( @{ $cfg{components} } ) {
            say $cfg{deb}{$arch}, $cfg{uri}, $dist, $component;
            for my $extra ( @{ $cfg{'extra-dists'} } ) {
                say $cfg{deb}{$arch}, $cfg{uri}, "$dist$extra", $component
            }
        }
        for my $extra ( keys %{ $cfg{'debian-installer'} } ) {
            for my $component ( @{ $cfg{'debian-installer'}{$extra} } ) {
                say $cfg{deb}{$arch}, $cfg{uri}, "$dist$extra", "$component/debian-installer";
            }
        }
    }
}

__DATA__
############# config ##################
#
# set base_path    /var/spool/apt-mirror
#
# if you change the base path you must create the directories below with write privileges
#
# set mirror_path  $base_path/mirror
# set skel_path    $base_path/skel
# set var_path     $base_path/var
# set cleanscript $var_path/clean.sh
set defaultarch i386 
# set postmirror_script $var_path/postmirror.sh
set run_postmirror 0
set nthreads     20
set _tilde 0
#
############# end config ##############

clean http://ftp.caliu.cat/ubuntu

