#!/bin/sh

WAN=eth3
LAN=eth2

# Flush all the rules in filter and nat tables
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain

# Enable NAT
iptables --table nat --append POSTROUTING --out-interface "$WAN" -j MASQUERADE
iptables --append FORWARD --in-interface "$LAN" -j ACCEPT
echo 1 > /proc/sys/net/ipv4/ip_forward
