#!/bin/sh

RUN_AS_APT_MIRROR="su - apt-mirror -c"
DISTS_ALIVE="lucid precise raring saucy"
MIRROR="http://ftp.caliu.cat"
WGET="wget -q -r -l 1"

n=1
for dist in ${DISTS_ALIVE}
do
    for dir in ${dist} ${dist}-updates ${dist}-security
    do
        $RUN_AS_APT_MIRROR "cd mirror && ${WGET} ${MIRROR}/ubuntu/dists/${dir}/main/dist-upgrader-all/current/"
        if [ $? -eq 0 ]
        then
            echo "ok $n - $dir"
        else
            echo "ok $n # skip $dir may not exist yet"
        fi
        total=$n
        n=`expr $n + 1`
    done
done
echo 1..$total
